<script lang="ts" src="https://cdn.jsdelivr.net/npm/apexcharts">
    import type { ApexOptions } from "apexcharts";
  import {
    Chart,
    Card,
    A,
    Button,
    Dropdown,
    DropdownItem,
    Popover,
  } from "flowbite-svelte";
  import {
    InfoCircleSolid,
    ChevronRightOutline,
    ChevronDownOutline,
    FileLinesSolid,
  } from "flowbite-svelte-icons";

  import { Avatar, Tooltip } from 'flowbite-svelte';

  import { Progressbar } from 'flowbite-svelte';

  let options: ApexOptions = {
    chart: {
      height: "400px",
      maxWidth: "100%",
      type: "line",
      fontFamily: "Inter, sans-serif",
      dropShadow: {
        enabled: false,
      },
      toolbar: {
        show: false,
      },
    },
    tooltip: {
      enabled: true,
      x: {
        show: false,
      },
    },
    dataLabels: {
      enabled: false,
    },
    stroke: {
      width: 6,
      curve: "smooth",
    },
    grid: {
      show: true,
      strokeDashArray: 4,
      padding: {
        left: 2,
        right: 2,
        top: -26,
      },
    },
    series: [
      {
        name: "Points",
        data: [230, 234, 229, 230, 239, 231],
        color: "#364C38",
      },
      {
        name: "Earnings in €",
        data: [230, 229, 227, 228, 234, 229],
        color: "#9CE1A2",
      },
    ],
    legend: {
      show: false,
    },
    xaxis: {
      categories: [
        "01 Feb",
        "02 Feb",
        "03 Feb",
        "04 Feb",
        "05 Feb",
        "06 Feb",
        "07 Feb",
      ],
      labels: {
        show: true,
        style: {
          fontFamily: "Inter, sans-serif",
          cssClass: "text-xs font-normal fill-gray-500 dark:fill-gray-400",
        },
      },
      axisBorder: {
        show: false,
      },
      axisTicks: {
        show: false,
      },
    },
    yaxis: {
      show: false,
    },
  };
</script>

<Progressbar progress="34" labelOutside="Level 2" color= "green"/>


<!-- hier brauchen wir wir ne statistik und ein leaderboard	 -->
<Card>
  <div class="flex justify-between mb-5">
    <div class="grid gap-4 grid-cols-2">
      <div>
        <h5 class="inline-flex items-center text-gray-500 dark:text-gray-400 leading-none font-normal mb-2">
          Points
          <InfoCircleSolid id="b1" class="w-3 h-3 text-gray-400 hover:text-gray-900 dark:hover:text-white cursor-pointer ms-1" />
          <Popover triggeredBy="#b1" class="text-sm text-gray-500 bg-white border border-gray-200 rounded-lg shadow-sm w-72 dark:bg-gray-800 dark:border-gray-600 dark:text-gray-400 z-10">
            <div class="p-3 space-y-2">
              <h3 class="font-semibold text-gray-900 dark:text-white">Clicks growth - Incremental</h3>
              <p>Report helps navigate cumulative growth of community activities. Ideally, the chart should have a growing trend, as stagnating chart signifies a significant decrease of community activity.</p>
              <h3 class="font-semibold text-gray-900 dark:text-white">Calculation</h3>
              <p>For each date bucket, the all-time volume of activities is calculated. This means that activities in period n contain all activities up to period n, plus the activities generated by your community in period.</p>
              <A href="/"
                >Read more
                <ChevronRightOutline class="w-2 h-2 ms-1.5" /></A>
            </div>
          </Popover>
        </h5>
        <p class="text-gray-900 dark:text-white text-2xl leading-none font-bold">846</p>
      </div>
      <div>
        <h5 class="inline-flex items-center text-gray-500 dark:text-gray-400 leading-none font-normal mb-2">
          Earnings
          <InfoCircleSolid id="b2" class="w-3 h-3 text-gray-400 hover:text-gray-900 dark:hover:text-white cursor-pointer ms-1" />
          <Popover triggeredBy="#b2" class="text-sm text-gray-500 bg-white border border-gray-200 rounded-lg shadow-sm w-72 dark:bg-gray-800 dark:border-gray-600 dark:text-gray-400 z-10">
            <div class="p-3 space-y-2">
              <h3 class="font-semibold text-gray-900 dark:text-white">CPC growth - Incremental</h3>
              <p>Report helps navigate cumulative growth of community activities. Ideally, the chart should have a growing trend, as stagnating chart signifies a significant decrease of community activity.</p>
              <h3 class="font-semibold text-gray-900 dark:text-white">Calculation</h3>
              <p>For each date bucket, the all-time volume of activities is calculated. This means that activities in period n contain all activities up to period n, plus the activities generated by your community in period.</p>
              <A href="/">Read more <ChevronRightOutline class="w-2 h-2 ms-1.5" /></A>
            </div>
          </Popover>
        </h5>
        <p class="text-gray-900 dark:text-white text-2xl leading-none font-bold">$5.40</p>
      </div>
    </div>
    <div>
      <Button color="light" class="px-3 py-2">Last week<ChevronDownOutline class="w-2.5 h-2.5 ms-1.5" /></Button>
      <Dropdown class="w-40">
        <DropdownItem>Yesterday</DropdownItem>
        <DropdownItem>Today</DropdownItem>
        <DropdownItem>Last 7 days</DropdownItem>
        <DropdownItem>Last 30 days</DropdownItem>
        <DropdownItem>Last 90 days</DropdownItem>
      </Dropdown>
    </div>
  </div>
  <Chart {options} />
  <!---
  <div class="grid grid-cols-1 items-center border-gray-200 border-t dark:border-gray-700 justify-between mt-2.5">
    <div class="pt-5">
      <Button href="/" class="px-4 py-2.5 text-sm font-medium text-white inline-flex items-center bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:outline-none focus:ring-primary-300 rounded-lg text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">
        <FileLinesSolid class="w-3.5 h-3.5 text-white me-2" />
        View full report
      </Button>
    </div>
  </div>
-->
</Card>



<div class="flex justify-center">
  <div class="flex items-center flex-col mr-4">
    <img src="https://cdn.anisearch.de/images/character/cover/50/50034_400.webp" alt="Profilbild 1" class="w-16 h-16 rounded-full mb-2">
    <p class="text-center">#1</p>
  </div>
  <div class="flex items-center flex-col mr-4">
    <img src="https://www.listchallenges.com/f/items/93eae3ce-8f56-4394-acea-df025180e030.jpg" alt="Profilbild 2" class="w-16 h-16 rounded-full mb-2">
    <p class="text-center">#2</p>
  </div>
  <div class="flex items-center flex-col mr-4">
    <img src="https://c02.purpledshub.com/uploads/sites/62/2022/05/psyduck-249ddf6.jpg?webp=1&w=1200" alt="Profilbild 3" class="w-16 h-16 rounded-full mb-2">
    <p class="text-center">#3</p>
  </div>
  <div class="flex items-center flex-col">
    <img src="https://st3.depositphotos.com/9998432/13335/v/450/depositphotos_133352156-stock-illustration-default-placeholder-profile-icon.jpg" alt="Profilbild 3" class="w-16 h-16 rounded-full mb-2">
    <p class="text-center">#34.902</p>
  </div>
</div>

<style>
  /* CSS-Stile für den Button */
  #progress {
    background-color: blue; /* Hintergrundfarbe des Buttons */
    color: white; /* Textfarbe des Buttons */
    /* Weitere Stile hier nach Bedarf */
  }

</style>
